Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  # servername
  config.vm.provider "virtualbox" do |v|
    v.name = "serverb"
  end


  # Identify which Vagrant box to use
  config.vm.box = "centos/7"
  #config.vm.box_url = "http://content.example.com/ansible2.0/x86_64/dvd/vagrant/rhel-server-libvirt-7.1-1.x86_64.box"

  #define ip
  # config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "mynetwork"
  config.vm.network "private_network", ip: "192.168.50.5", virtualbox__intnet: "mynetwork"

  # Define host settings
  config.vm.hostname = "serverb.lab.example.com"

  # Define sync folder(s)

  # Define shell provisioner
  config.vm.provision "shell", path: "setup.sh"

  # Define ansible provisioner

end
